version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisdata:/data
    networks:
      - internal_network

  wallet-api:
    build:
      context: .
      dockerfile: docker/wallet-api/Dockerfile
    container_name: wallet-api
    ports:
      - "3000:3000"
    networks:
      - internal_network
    depends_on:
      - redis

  wallet-processor:
    build:
      context: .
      dockerfile: docker/wallet-processor/Dockerfile
    container_name: wallet-processor
    ports:
      - "3001:3001"
    networks:
      - internal_network
    depends_on:
      - redis

volumes:
  redisdata:

networks:
  internal_network:
    name: internal_network