version: "3.8"
services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: wallet
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - internal_network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisdata:/data
    networks:
      - internal_network

  wallet-api:
    build:
      context: .
      dockerfile: docker/wallet-api/Dockerfile
    container_name: wallet-api
    ports:
      - "3000:3000"
    networks:
      - internal_network
    depends_on:
      - redis
      - mongodb

  wallet-processor:
    build:
      context: .
      dockerfile: docker/wallet-processor/Dockerfile
    container_name: wallet-processor
    ports:
      - "3001:3001"
    networks:
      - internal_network
    depends_on:
      - redis
      - mongodb

volumes:
  redisdata:
  dbdata6:

networks:
  internal_network:
    name: internal_network